package com.example.rhythmcrowd.Model;

public class Constants {
    public static final String POPULAR = "popular";
    public static final String LATEST = "latest";
    public static final String FOLLOWING = "following";
    public static final String FOLLOWERS = "followers";
    public static final String SEARCH = "search";
    public static final String POST_REF = "post";
    public static final String COMMENTS_REF = "comments";
    public static final String PROFILE_POST_REF = "profilePost";
    public static final String USERS_REF = "users";
    public static final String NUM_LIKES = "numLikes";
    public static final String NUM_COMMENTS = "numComments";
    public static final String NUM_FOLLOWERS = "numFollowers";
    public static final String NUM_FOLLOWING = "numFollowing";
    public static final String COMMENT_TXT = "commentTxt";
    public static final String POST_TXT = "postTxt";
    public static final String PROFILE_POST_TXT = "profilePostTxt";
    public static final String TIMESTAMP = "timestamp";
    public static final String DATE_CREATED = "dateCreated";
    public static final String DATE_CONNECTION_STARTED = "dateFollowStarted";
    public static final String USERNAME = "username";
    public static final String BIO = "bio";
    public static final String EMAIL = "email";
    public static final String FIRSTNAME = "firstName";
    public static final String LASTNAME = "lastName";
    public static final String CITY = "city";
    public static final String STATE = "state";
    public static final String USER_ID = "userId";
    public static final String DOCUMENT_KEY = "documentId";
    public static final String SONGS = "songs";
    public static final String SCHEDULE = "schedule";
    public static final String MERCH = "merch";
    public static final String SOCIAL = "social";
    public static final String TRENDING = "trending";
    public static final String ACTIVITY = "activity";
    public static final String CATEGORY = "category";
    public static final String GENRE = "genre";
    public static final String NAME = "nameAZ";
    public static final String RECOMMENDED = "recommended";
}
